[package]
name = "aipoint-share"
version = "1.1.1"
description = "AIPoint Share — device-to-device file transfer"
authors = ["Soubick Das"]
edition = "2021"

[lib]
name = "aipoint_share_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-autostart = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
if-addrs = "0.13"
rand = "0.8"
dirs = "5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
